import Head from "next/head";
import Link from "next/link";
export default function index() {
  return (
    <>
      <Head>
        <title>My products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
}
