import Image from "next/legacy/image";
import styles from "./page.module.css";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <nav>
          <Link href="/products">Products</Link>
        </nav>
      </header>
      <footer>This is the footer</footer>
    </>
  );
}
